# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Article'),
        ),
        migrations.AlterUniqueTogether(
            name='imagelink',
            unique_together=set([('article', 'role', 'image')]),
        ),
    ]
